openapi: 3.0.3
info:
  title: Certificate Service API
  description: Certificate Service API
  version: 1.0.0
servers:
  - url: 'https'

paths:
  /users:
    get:
      summary: List all users
      description: The list of all users is only visible for a user flagged as uploader.
      tags:
        - users
      operationId: listUsers
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

  /users/{username}/certificate:
    parameters:
      - $ref: '#/components/parameters/username'
    post:
      summary: Upload a new certificate for the specified user
      tags:
        - certificates
      operationId: uploadCertificate
      security:
        - basicAuth: [ ]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

  /certificates:
    get:
      summary: Download the certificate for the current user
      tags:
        - certificates
      operationId: downloadCertificate
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: OK
          content:
            application/binary:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

components:

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    UserDto:
      type: object
      required:
        - username
      properties:
        username:
          type: string


    CertificateDto:
      type: object
      required:
        - id
        - created
        - filename
        - fileSize
      properties:
        id:
          type: string
          format: uuid
        created:
          type: string
          format: date-time
        filename:
          type: string
        fileSize:
          type: integer
          format: int64

  parameters:
    username:
      in: path
      name: username
      required: true
      schema:
        type: string
      description: the name of the user
